run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

linters:
  disable-all: true
  enable:
    - errcheck       # 检查未检查的错误
    - gosimple       # 简化代码
    - govet          # 静态分析
    - ineffassign    # 检测无效赋值
    - staticcheck    # 高级静态分析
    - unused         # 检查未使用的代码
    - gofmt          # 代码格式化
    - goimports      # 自动格式化 imports
    - misspell       # 拼写检查
    - revive         # 快速、可配置的 linter

linters-settings:
  errcheck:
    check-blank: true
    check-type-assertions: true
  
  govet:
    enable-all: true
    settings:
      shadow:
        strict: true
  
  staticcheck:
    checks: ["all"]

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck